# Dataset Distributions

This notebook investigates the distributions of key political identity-building categories related to political actors, based on dataset metadata.  

### Categories of Interest
- *Membership*: Political parties, parliamentary groups, ministers, and government affiliations  
- *Ideology*: Party families, GAL–TAN positionings (CHES variables)  
- *Group Relations*: Party status (Coalition vs. Opposition), political orientation (LREGEN, LRECON, Wikipedia classifications)  

###Purpose

The goal of this exploration is to:
1. *Investigate basic distributions* to gain an overview of the dataset’s structure  
2. *Identify trends* within the political landscape of the studied parliamentary period  

### Focus Areas
- *Party activity*: How political parties and groups are distributed and represented  
- *Sentiment trends*: Patterns in sentiment across different ideological or group categories  

--- 

Sample input: 
Pre-processed dataset [ParlaMint-SI_5.1_master.tsv](../Sample/Datasets/ParlaMint-SI_5.1_master.tsv)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../Datasets/ParlaMint-SI_5.1_master.tsv", sep="\t", encoding="utf-8")
df.head()

,ID,Text,Date,Term,Meeting,Subcorpus,Speaker_role,Speaker_MP,Speaker_minister,Speaker_party,...,Speaker_name,Speaker_gender,Speaker_birth,Topic,Senti_3,Senti_6,Senti_n,Sents,Words,Tokens
0,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u1,Spoštovani kolegice poslanke in kolegi poslanc...,2014-01-24,6. mandat,Izredna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Other,Neutral,neutral positive,3.40,24,311,363
1,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u2,"Spoštovani predsednik, spoštovani kolegice in ...",2014-01-24,6. mandat,Izredna,Reference,Regular,MP,notMinister,SDS,...,"Vizjak, Andrej",M,1964,Energy,Negative,mixed negative,0.80,68,1638,1889
2,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u3,Hvala za dopolnilno obrazložitev. Predlog prip...,2014-01-24,6. mandat,Izredna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Housing,Neutral,neutral positive,2.97,3,28,31
3,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u4,"Hvala lepa za besedo, gospod predsednik. Spošt...",2014-01-24,6. mandat,Izredna,Reference,Regular,MP,notMinister,SD,...,"Bevk, Samo",M,1956,Energy,Neutral,neutral negative,2.08,31,711,785
4,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u5,Hvala tudi vam za podano poročilo. Gospod Samo...,2014-01-24,6. mandat,Izredna,Reference,Chairperson,MP,notMinister,SD,...,"Veber, Janko",M,1960,Housing,Neutral,neutral positive,3.00,2,20,24

In [3]:
print(df.shape)
df.describe(include="all")

(420, 24)

,ID,Text,Date,Term,Meeting,Subcorpus,Speaker_role,Speaker_MP,Speaker_minister,Speaker_party,...,Speaker_name,Speaker_gender,Speaker_birth,Topic,Senti_3,Senti_6,Senti_n,Sents,Words,Tokens
count,420,420,420,420,420,420,420,420,420,420,...,420,420,420,420,420,420,420.000000,420.000000,420.000000,420.000000
unique,420,405,4,4,2,2,2,2,2,18,...,104,2,43,20,3,6,NaN,NaN,NaN,NaN
top,ParlaMint-SI_2014-01-24-SDZ6-Izredna-53.u1,"Hvala. Gospod minister, izvolite.",2014-01-24,6. mandat,Izredna,Reference,Chairperson,MP,notMinister,SDS,...,"Komar, Polonca",M,1943,Other,Neutral,neutral positive,NaN,NaN,NaN,NaN
freq,1,8,167,167,247,340,213,397,388,114,...,62,317,67,202,269,227,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.112119,12.657143,231.580952,269.340476
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.291469,17.804067,385.628496,449.972644
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,2.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.660000,2.000000,10.000000,13.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.900000,5.000000,54.500000,65.500000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,17.000000,358.250000,409.250000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.950000,144.000000,3532.000000,4106.000000

In [ ]:
reg_speeches = df[df["Speaker_role"] == "Regular"]
party = df["Speaker_party"].unique()

print("No. of all speeches: ", len(df))
print("Speeches of regular speakers: ", len(reg_speeches), "%: ", (len(reg_speeches)/len(df))*100)
print("Earliest date: ", df["Date"].min())
print("Latest date: ", df["Date"].max())
print("No. of unique parties ", len(party), party)
print("Sentiment 6-class: ", df["Senti_6"].value_counts())
print("Sentiment 3-class: ", df["Senti_3"].value_counts()
)

No. of all speeches:  420
Speeches of regular speakers:  207 %:  49.28571428571429
Earliest date:  2000-10-27
Latest date:  2022-01-13
No. of unique parties  18 ['SD' 'SDS' '-' 'DeSUS' 'NSi' 'DL' 'PS' 'SLS' 'NeP' 'NP' 'Konkretno' 'SNS'
 'LMŠ' 'Levica' 'SAB' 'IMNS' 'LDS' 'SLS+SKD']
Sentiment 6-class:  Senti_6
neutral positive    227
negative             99
neutral negative     42
mixed negative       32
mixed positive       17
positive              3
Name: count, dtype: int64
Sentiment 3-class:  Senti_3
Neutral     269
Negative    131
Positive     20
Name: count, dtype: int64

In [5]:
# Removing procedural speeches for the analysis, rechecking base characteristics
df = df[df["Speaker_role"] == "Regular"]

print("No. of all speeches: ", len(df))
print("Earliest date: ", df["Date"].min())
print("Latest date: ", df["Date"].max())
print("No. of unique parties ", len(party), party)
print("Sentiment 6-class: ", df["Senti_6"].value_counts())
print("Sentiment 3-class: ", df["Senti_3"].value_counts())

No. of all speeches:  207
Earliest date:  2000-10-27
Latest date:  2022-01-13
No. of unique parties  18 ['SD' 'SDS' '-' 'DeSUS' 'NSi' 'DL' 'PS' 'SLS' 'NeP' 'NP' 'Konkretno' 'SNS'
 'LMŠ' 'Levica' 'SAB' 'IMNS' 'LDS' 'SLS+SKD']
Sentiment 6-class:  Senti_6
negative            98
mixed negative      31
neutral positive    31
neutral negative    29
mixed positive      15
positive             3
Name: count, dtype: int64
Sentiment 3-class:  Senti_3
Negative    129
Neutral      60
Positive     18
Name: count, dtype: int64

In [40]:
# Table with overview of speeches, sentiment avg and sent percentages
#mapping = {"Far right":"FR", 
# "Right to far right": "R-FR", 
# "Centre-right":"CR", 
# "Centre to centre-left":"C-CR", 
# "Centre":"C", 
# "Centre to centre-left":"C-CL", 
# "Centre-left":"CL", 
# "Left":"L", 
# "Left to far left": "L-FL", 
# "Far left": "FL", 
# "-":"-", }

status = df.groupby(['Speaker_party','Party_status']).size().unstack(fill_value=0)
status.columns = ['Speech (U)', 'Speech (C)', 'Speech (O)']
avg_sent = df.groupby(['Speaker_party', 'Party_status'])["Senti_n"].mean().unstack(fill_value=0)
avg_sent.columns = ['Avg. Sent (U)', 'Avg. Sent (C)', 'Avg. Sent (O)']
sent_count = df.groupby(['Speaker_party', df['Senti_3']]).size().unstack(fill_value=0)
sent_percent = sent_count.div(sent_count.sum(axis=1), axis=0) * 100

party_metadata = df[['Speaker_party', 'Party_orientation']].drop_duplicates().set_index('Speaker_party')


overview = (
    status.merge(avg_sent, on="Speaker_party", how="left")
    .merge(sent_percent, on="Speaker_party", how="left")
    .merge(party_metadata, on="Speaker_party", how='left')
    .reset_index()
    )

overview.rename(columns={
    'Positive': '% Positive',
    'Neutral': '% Neutral',
    'Negative': '% Negative'
}, inplace=True)


overview['Total Speeches'] = overview['Speech (U)'] + overview['Speech (C)'] + overview['Speech (O)']
total_speeches = overview['Total Speeches'].sum()
overview['Speech %'] = (overview['Total Speeches'] / total_speeches) * 100
overview = overview[['Speaker_party', 'Party_orientation', 'Total Speeches', 'Speech %', 'Speech (C)', 'Speech (O)','Speech (U)',
               'Avg. Sent (C)', 'Avg. Sent (O)','Avg. Sent (U)', '% Positive', '% Neutral', '% Negative']]

cols_to_format = [
    'Speech %', 'Avg. Sent (C)', 'Avg. Sent (O)', 'Avg. Sent (U)',
    '% Positive', '% Neutral', '% Negative'
]

for col in cols_to_format:
    overview[col] = overview[col].map(lambda x: f"{x:.1f}")

overview

,Speaker_party,Party_orientation,Total Speeches,Speech %,Speech (C),Speech (O),Speech (U),Avg. Sent (C),Avg. Sent (O),Avg. Sent (U),% Positive,% Neutral,% Negative
0,-,-,21,10.1,0,0,21,0.0,0.0,2.2,14.3,61.9,23.8
1,DL,Centre to centre-right,4,1.9,4,0,0,0.6,0.0,0.0,0.0,0.0,100.0
2,DeSUS,Centre to centre-left,11,5.3,11,0,0,1.7,0.0,0.0,27.3,18.2,54.5
3,IMNS,-,3,1.4,0,0,3,0.0,0.0,0.8,0.0,33.3,66.7
4,Konkretno,Centre,2,1.0,2,0,0,3.3,0.0,0.0,50.0,50.0,0.0
5,LDS,Centre to centre-left,19,9.2,5,14,0,2.4,0.3,0.0,0.0,21.1,78.9
6,LMŠ,Centre to centre-left,3,1.4,0,3,0,0.0,2.1,0.0,0.0,66.7,33.3
7,Levica,Left,4,1.9,0,4,0,0.0,0.5,0.0,0.0,0.0,100.0
8,NP,-,2,1.0,0,0,2,0.0,0.0,0.2,0.0,0.0,100.0
9,NSi,Centre-right,13,6.3,7,6,0,3.0,0.8,0.0,23.1,38.5,38.5
10,NeP,-,1,0.5,0,0,1,0.0,0.0,0.0,0.0,0.0,100.0
11,PS,Centre to centre-left,12,5.8,10,0,2,0.3,0.0,3.0,0.0,25.0,75.0
12,SAB,Centre-left,3,1.4,0,3,0,0.0,1.4,0.0,0.0,33.3,66.7
13,SD,Centre-left,29,14.0,17,12,0,1.0,1.5,0.0,3.4,31.0,65.5
14,SDS,Right,59,28.5,23,36,0,2.1,0.4,0.0,8.5,22.0,69.5
15,SLS,Centre-right,5,2.4,3,2,0,3.1,0.8,0.0,40.0,0.0,60.0
16,SLS+SKD,Centre-right,3,1.4,3,0,0,3.1,0.0,0.0,0.0,100.0,0.0
17,SNS,Right to far-right,13,6.3,0,13,0,0.0,0.6,0.0,0.0,23.1,76.9

In [42]:
overview.to_latex("../Sample/Results/Tables/Overview_table.tex")