# Statistical analysis of the data

This notebook consists of statistical checks of the inspected variables, related to the hypothesis set for this part of analysis: 

RQ: How do selected manifestations of political identity (political parties, party status, political orientation) shape parliamentary discourse in terms of sentiment?

- H1. Coalition parties will consistently exhibit higher neutral/positive sentiment, while opposition parties will display more negativity, though intensity may vary across terms based on political events.
- H2: Changes in political orientation will correlate with sentiment shifts, with right/traditionalist parties showing higher negativity.
- H3: Negative sentiment will dominate parliamentary debates, with minor occurrences of other sentiment categories. Political crises, elections, or leadership changes will correlate with sentiment shifts.

In [1]:
import pandas as pd
import matplotlib.pyplot as pyplot
import seaborn as sns
import plotly.express as px
from scipy import stats

In [2]:
df = pd.read_csv("../Results/Datasets/ParlaMint-SI_Family.tsv", sep="\t", encoding="utf-8")
df.head()

,ID,Text,Date,Term,Meeting,Subcorpus,Speaker_role,Speaker_MP,Speaker_minister,Speaker_party,...,Speaker_birth,Topic,Senti_3,Senti_6,Senti_n,Sents,Words,Tokens,Grouped_parties,Family
0,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u1,Spoštovane kolegice poslanke in kolegi poslanc...,2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,1960,Mix,Neutral,neutral positive,3.21,25,504,570,ZLSD/SD,Socialist
1,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u2,"Hvala lepa za besedo. Zdaj Vlada predlaga, da ...",2014-01-27,6. mandat,Redna,Reference,Regular,MP,notMinister,SDS,...,1956,Macroeconomics,Negative,negative,0.00,25,419,481,SDS,Conservatives
2,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u3,Hvala tudi vam. O tej zahtevi ni razprave in o...,2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,1960,Mix,Neutral,neutral positive,3.10,18,265,310,ZLSD/SD,Socialist
3,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u4,"Hvala lepa za besedo. To, kar se dogaja z nove...",2014-01-27,6. mandat,Redna,Reference,Regular,MP,notMinister,SDS,...,1956,Public Lands,Negative,negative,0.00,28,592,684,SDS,Conservatives
4,ParlaMint-SI_2014-01-27-SDZ6-Redna-21.u5,"Hvala. Naj vas opozorim, da tudi o tej zahtevi...",2014-01-27,6. mandat,Redna,Reference,Chairperson,MP,notMinister,SD,...,1960,Other,Neutral,neutral negative,1.84,28,405,471,ZLSD/SD,Socialist

### H1: Coalition parties more neutral/positive; opposition more negative

In [3]:
df_party_year = df.groupby(["Speaker_party", "Term", "Party_status"])["Senti_n"].mean().reset_index()
df_party_year.head()

  Speaker_party       Term Party_status   Senti_n
0             -  3. mandat            -  3.765000
1             -  4. mandat            -  2.453922
2             -  6. mandat            -  2.055132
3             -  8. mandat            -  2.696465
4            DL  6. mandat    Coalition  2.595528

In [7]:
coal = df_party_year[df_party_year["Party_status"] == "Coalition"]["Senti_n"]
oppo = df_party_year[df_party_year["Party_status"] == "Opposition"]["Senti_n"]
print(len(coal))#16
print(len(oppo))#14

stats.ttest_ind(coal, oppo, equal_var=False)

16
14

TtestResult(statistic=np.float64(4.2850272353038745), pvalue=np.float64(0.00041746927463775114), df=np.float64(18.592910347252673))